language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.2

install:
  - composer install --ignore-platform-reqs --no-interaction

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - composer test:coverage

after_script:
  - travis_retry composer upload-coverage

cache:
  directories:
  - $HOME/.composer/cache
  - vendor